# Generated by Django 6.1 on 2026-08-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_preparation_time',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
