# Generated by Django 6.1 on 2026-08-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_order_estimated_preparation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preparing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
