# Generated by Django 6.1 on 2026-09-03 05:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
