# Generated by Django 6.1 on 2026-10-08 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_order_invoice_token'),
        ('menu', '0009_alter_food_price_alter_foodvariant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.foodvariant'),
        ),
    ]
