# Generated by Django 6.1 on 2026-08-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='food',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
