# Generated by Django 6.1 on 2026-10-04 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_food_preparation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_available', models.BooleanField(default=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='menu.food')),
            ],
        ),
    ]
