# Generated by Django 6.1 on 2026-10-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_foodvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
