# Generated by Django 6.1 on 2026-10-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_foodvariant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='foodvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
